---
- name: Setting up application service
  user: root
  hosts: red, blue, green
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Remove locks
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock-frontend
        - /var/lib/apt/lists/lock
        - /var/lib/dpkg/lock
    - name: Fix dpkg
      ansible.builtin.shell:
        cmd: dpkg --configure -a
    - name: Adding Gcreds
      ansible.builtin.copy:
        src: ~/gcreds.json
        dest: /usr/share/.gcreds
        group: docker
        owner: nomad
    - name:
      ansible.builtin.shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - name: Install Apt Dependencies
      ansible.builtin.apt:
        update_cache: true
    - name: Adding nomad working directory
      ansible.builtin.file:
        path: /var/opt/loki
        state: directory
        owner: nomad
        mode: '0775'