---
- name: Setting up application service
  user: root
  hosts: green
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Allow 3000
      community.general.ufw:
        rule: allow
        port: '3000'
        proto: tcp
    - name: Frontend Service
      community.docker.docker_container:
        name: "lostcities-frontend"
        image: "ghcr.io/lostcities-cloud/lostcities-frontend"
        state: started
        pull: yes
        ports:
          - "3000:3000"
        memory: '200M'


