---
- name: Setting up consul
  user: root
  hosts: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Join Consul
    ansible.builtin.shell: |
      nomad server join blue.{{domain}}