---
- name: Prometheus Instance
  user: root
  hosts: red
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Allow 9090
      community.general.ufw:
        rule: allow
        port: '9090'
        proto: tcp

    - name: create opt prometheus
      ansible.builtin.file:
        path: /opt/prometheus/
        state: directory
        mode: '0755'

    - name: Adding prometheus config
      ansible.builtin.copy:
        src: ./prometheus-config.yml
        dest: /opt/prometheus/prometheus.yml
    - name: Prometheus service
      community.docker.docker_container:
        name: "prometheus"
        image: "prom/prometheus:v2.31.1"
        command: "--config.file=/etc/prometheus/prometheus.yml"
        volumes:
          - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        state: started
        ports:
          - "9090"
        memory: '100M'


