---
- name: Setting up vault
  user: root
  hosts: red, blue, green
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Apt Dependencies
      ansible.builtin.apt:
        name: vault
        update_cache: false

    - name: Add vault user
      ansible.builtin.user:
        name: vault
        home: /etc/vault.d
        system: yes
        shell: /bin/false
        append: yes

    - name: Allow 8200
      community.general.ufw:
        rule: allow
        port: '8200'
        proto: tcp
    - name: Allow 8201
      community.general.ufw:
        rule: allow
        port: '8201'
        proto: tcp

    - name: Adding nomad working directory
      ansible.builtin.file:
        path: /opt/vault
        state: directory
        owner: vault
        mode: '0775'
    - name: install frontend
      ansible.builtin.shell: |
        export VAULT_ADDR='http://127.0.0.1:8200'
        vault operator init

    - name: Adding nomad service
      ansible.builtin.copy:
        src: ./nomad.service
        dest: /etc/systemd/system/nomad.service
    - name: Adding nomad config
      ansible.builtin.template:
        src: ./nomad.hcl
        dest: /etc/nomad.d/nomad.hcl
    - name: Allow 4646
      community.general.ufw:
        rule: allow
        port: '4646'
        proto: tcp
    - name: Allow 4647
      community.general.ufw:
        rule: allow
        port: '4647'
        proto: tcp
    - name: Allow 4648 udp
      community.general.ufw:
        rule: allow
        port: '4648'
        proto: udp
    - name: Allow 4648 tcp
      community.general.ufw:
        rule: allow
        port: '4648'
        proto: tcp
    - name: Start nomad
      ansible.builtin.systemd:
        state: started
        name: nomad
