---
- name: Setting up consul
  user: root
  hosts: red, blue, green
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name:
    ansible.builtin.shell: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - name: Install Apt Dependencies
    ansible.builtin.apt:
      name: consul
  - name: Install Apt Dependencies
    ansible.builtin.apt:
      name: consul-template
  - name: Add consul user
    ansible.builtin.user:
      name: consul
      home: /etc/consul.d
      system: yes
      shell: /bin/false
  - name:
    ansible.builtin.shell: |
      mkdir -p /opt/consul
      chown consul -R /opt/consul/