---
- name: Setting up consul
  user: root
  hosts: red, blue, green, yellow
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Install Apt Dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
    with_items:
      - consul
      - consul-template
  - name: Add consul user
    ansible.builtin.user:
      name: consul
      home: /etc/consul.d
      system: yes
      shell: /bin/false
  - name: Adding consul working directory
    ansible.builtin.file:
      path: /opt/consul
      state: directory
      owner: consul
      mode: '0755'