---
- name: Setting up consul
  user: root
  hosts: blue
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Join Consul
    ansible.builtin.shell: |
      consul join {{ green_ipv4 }}
      consul join {{ red_ipv4 }}
      consul join {{ yellow_ipv4 }}
      consul join {{ white_ipv4 }}
