---
- name: Setting up application service
  user: root
  hosts: nginx
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Allow 3000
      community.general.ufw:
        rule: allow
        port: '3000'
        proto: tcp

    - name: Copy frontend
      ansible.builtin.file:
        path: /opt/lostcities
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Remove old frontend
      ansible.builtin.file:
        path: /opt/lostcities/frontend
        state: absent

    - name: install frontend
      ansible.builtin.shell: |
          cd /root/ 
          curl -L --max-redirs 5 https://github.com/lostcities-cloud/lostcities-frontend/releases/download/latest/lostcities-cloud-lostcities-frontend-0.1.0.tgz -O
          tar zxvf lostcities-cloud-lostcities-frontend-0.1.0.tgz package/
          mv /root/package /opt/lostcities/frontend 

