---
- name: Setting up consul
  user: root
  hosts: red, blue, green, yellow, white
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Join Consul
    ansible.builtin.shell: |
      nomad server join {{ blue_ipv4 }}