---
- name: Setting up nomad
  user: root
  hosts: red, blue, green, yellow
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install Apt Dependencies
      ansible.builtin.apt:
        name: nomad
        update_cache: false
    - name: Add nomad user
      ansible.builtin.user:
        name: nomad
        home: /etc/nomad.d
        system: yes
        shell: /bin/false
        append: yes
        groups: docker

    - name: Adding nomad working directory
      ansible.builtin.file:
        path: /var/opt/loki
        state: directory
        owner: nomad
        mode: '0775'

    - name: Adding Gcreds
      ansible.builtin.copy:
        src: ~/gcreds.json
        dest: /usr/share/.gcreds
        group: docker
        owner: nomad

    - name: Adding nomad working directory
      ansible.builtin.file:
        path: /opt/nomad
        state: directory
        owner: nomad
        mode: '0775'
    - name: Adding nomad service
      ansible.builtin.copy:
        src: ./nomad.service
        dest: /etc/systemd/system/nomad.service
    - name: Adding nomad config
      ansible.builtin.template:
        src: ./nomad.hcl
        dest: /etc/nomad.d/nomad.hcl
    - name: Allow 4646
      community.general.ufw:
        rule: allow
        port: '4646'
        proto: tcp
    - name: Allow 4647
      community.general.ufw:
        rule: allow
        port: '4647'
        proto: tcp
    - name: Allow 4648 udp
      community.general.ufw:
        rule: allow
        port: '4648'
        proto: udp
    - name: Allow 4648 tcp
      community.general.ufw:
        rule: allow
        port: '4648'
        proto: tcp
    - name: Start nomad
      ansible.builtin.systemd:
        state: restarted
        name: nomad
